version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: spring-mongodb
    container_name: spring-mongodb
    ports:
      - 8080:8080
    links:
      - mymongodb